name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm ci

      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: apple/pkl
          # TODO: Parameterise version
          # TODO: Test on range of Pkl versions using matrix
          version: 0.25.1
          file: pkl-linux-amd64
          target: /usr/bin
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: npm test
